Repository colobobo/client, pull requests merged in 2020-05, with the labels that each got.

#28 improve game start + add area + game tick POC
  package.json
  src/components/Area/index.scss
  src/components/Area/index.tsx
  src/components/admin/device/index.scss
  src/components/client/game/game.scss
  src/components/client/game/index.tsx
  src/components/client/room/index.scss
  src/components/client/room/index.tsx
  src/components/client/waitingRoom/index.scss
  src/components/client/waitingRoom/index.tsx
  src/redux/Area/index.ts
  src/redux/Game/index.ts
  src/redux/Room/index.ts
  src/redux/WebSocket/actions/subscribe/area.ts
  src/redux/WebSocket/actions/subscribe/game.ts
  src/redux/WebSocket/actions/subscribe/index.ts
  src/redux/WebSocket/socketMiddleware.ts
  src/redux/store.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#32 Game : add experiment with drag & drop
  package.json
  src/components/Area/index.scss
  src/components/DraggableElement/index.scss
  src/components/DraggableElement/index.tsx
  src/components/DraggableWrapper/index.tsx
  src/components/client/game/game.scss
  src/components/client/game/index.scss
  src/components/client/game/index.tsx
  src/redux/Game/index.ts
  src/redux/WebSocket/actions/emit/game.ts
  yarn.lock
Labels: enhancement

#33 [ADMIN] improve devices list
  src/components/admin/device/index.tsx
  src/components/admin/group/index.scss
  src/components/admin/group/index.tsx
  src/components/admin/groups/index.scss
  src/components/admin/groups/index.tsx
  src/components/admin/header/index.scss
  src/components/admin/header/index.tsx
  src/components/admin/home/index.scss
  src/components/admin/home/index.tsx
  src/components/admin/room/index.tsx
  src/components/admin/rooms/index.tsx
  src/components/client/landing/index.tsx
  src/config/groups.ts
  src/datas/devices.ts
  src/redux/Device/index.ts
  src/views/admin/group/index.tsx
  src/views/admin/groups/index.tsx
  src/views/admin/index.tsx
  src/views/admin/room/index.tsx
  src/views/admin/rooms/index.tsx
  src/views/client/index.scss
  src/views/client/index.tsx
  yarn.lock
Labels: admin, enhancement

#39 Connect first and last device screen
  package.json
  src/components/DraggableElement/index.scss
  src/components/DraggableElement/index.tsx
  src/components/DraggableWrapper/index.tsx
  src/components/GameCanvas/index.scss
  src/components/GameCanvas/index.tsx
  src/components/client/game/index.tsx
  src/redux/Game/index.ts
  yarn.lock
Labels: enhancement

#47 Refacto client according to server changes
  src/components/DraggableElement/index.tsx
  src/components/GameCanvas/index.tsx
  src/redux/Game/index.ts
  src/redux/Round/index.ts
  src/redux/Transition/index.ts
  src/redux/WebSocket/actions/emit/game.ts
  src/redux/WebSocket/actions/emit/index.ts
  src/redux/WebSocket/actions/emit/round.ts
  src/redux/WebSocket/actions/emit/transition.ts
  src/redux/WebSocket/actions/subscribe/game.ts
  src/redux/WebSocket/actions/subscribe/index.ts
  src/redux/WebSocket/actions/subscribe/round.ts
  src/redux/WebSocket/actions/subscribe/transition.ts
  src/redux/index.ts
  yarn.lock
Labels: structure

#48 Test new assets exports #46
  src/assets/worlds/mountain/background-1.png
  src/assets/worlds/mountain/background-2.png
  src/assets/worlds/mountain/decorations/bleeds/bottom.png
  src/assets/worlds/mountain/decorations/bleeds/top.png
  src/assets/worlds/mountain/decorations/bottom.png
  src/assets/worlds/mountain/decorations/top.png
  src/components/Area/index.scss
  src/components/GameBackground/index.tsx
  src/components/GameDecoration/index.scss
  src/components/GameDecoration/index.tsx
  src/components/GameDecorationBleed/index.scss
  src/components/GameDecorationBleed/index.tsx
  src/views/game/index.tsx
Labels: assets
